# Generated by Django 3.2.20 on 2024-08-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalog',
            new_name='BaseData',
        ),
    ]
