# Generated by Django 3.2.20 on 2024-08-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_catalog_basedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование объекта')),
                ('top_description', models.TextField(blank=True, null=True, verbose_name='Текст над названием')),
                ('down_description', models.TextField(blank=True, null=True, verbose_name='Текст под названием')),
                ('deadline', models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок сдачи')),
                ('jarlyk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ярлык')),
                ('about_before_slide', models.TextField(blank=True, null=True, verbose_name='Описание до слайдера')),
                ('about_after_slide', models.TextField(blank=True, null=True, verbose_name='Описание после слайдера')),
                ('category', models.CharField(blank=True, choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('dacha', 'Дача'), ('land', 'Земельный участок')], default='house', max_length=100, verbose_name='Категория недвижимости')),
                ('video_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок видео')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='Видео с YouTube')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Координаты на карте')),
                ('adres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес с текстом')),
                ('characteristic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Характеристика')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('advantages', models.CharField(blank=True, max_length=255, null=True, verbose_name='Преимущество')),
                ('deteil_description', models.TextField(blank=True, null=True, verbose_name='Детальное описание')),
            ],
        ),
        migrations.CreateModel(
            name='Old_Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование объекта')),
                ('category', models.CharField(blank=True, choices=[('apartment', 'Квартира'), ('house', 'Дом')], default='house', max_length=100, verbose_name='Категория недвижимости')),
                ('square', models.IntegerField(blank=True, null=True, verbose_name='Площадь')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('all_floor', models.IntegerField(blank=True, null=True, verbose_name='Всего этажей')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена объекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='Видео с YouTube')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Координаты на карте')),
                ('adres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес с текстом')),
                ('characteristic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Характеристика')),
                ('deteil_description', models.TextField(blank=True, null=True, verbose_name='Детальное описание')),
            ],
        ),
        migrations.DeleteModel(
            name='BaseData',
        ),
    ]
