# Generated by Django 5.1 on 2024-08-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_building_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='type',
            field=models.CharField(choices=[('1', 'Новая недвижимость'), ('2', 'Вторичное жильё')], default='1', max_length=100, verbose_name='Тип недвижимости'),
        ),
    ]
