# Generated by Django 5.1 on 2024-08-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image_slider',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назване страницы')),
                ('url_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('deskription_seo', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('key_word', models.TextField(blank=True, null=True, verbose_name='Ключевые слова')),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.building')),
            ],
        ),
    ]
