# Generated by Django 5.1 on 2024-08-26 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_building_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='user',
        ),
        migrations.AlterField(
            model_name='building',
            name='title',
            field=models.CharField(blank=True, default='Объект', max_length=255, null=True, verbose_name='Наименование объекта'),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Новая недвижимость'), ('2', 'Вторичное жильё')], default='1', max_length=100, verbose_name='Тип недвижимости')),
                ('category', models.CharField(choices=[('1', 'Комплексы (ЖК, Коттеджные поселки)'), ('2', 'Отдельные объекты (Вторичка, частные объявления)')], default='1', max_length=100, verbose_name='Категория недвижимости')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.type'),
        ),
    ]
