# Generated by Django 5.1 on 2024-08-26 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_building_user_alter_building_title_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='all_floor',
        ),
        migrations.RemoveField(
            model_name='building',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='building',
            name='price',
        ),
        migrations.RemoveField(
            model_name='building',
            name='square',
        ),
        migrations.AlterField(
            model_name='type',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OldBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Объект', max_length=255, null=True, verbose_name='Наименование объекта')),
                ('top_description', models.TextField(blank=True, null=True, verbose_name='Текст над названием')),
                ('down_description', models.TextField(blank=True, null=True, verbose_name='Текст под названием')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('about_before_slide', models.TextField(blank=True, null=True, verbose_name='Описание до слайдера')),
                ('about_after_slide', models.TextField(blank=True, null=True, verbose_name='Описание после слайдера')),
                ('category', models.CharField(blank=True, choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('dacha', 'Дача'), ('land', 'Земельный участок')], default='house', max_length=100, verbose_name='Категория недвижимости')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Координаты на карте')),
                ('adres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес с текстом')),
                ('characteristic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Характеристика')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('advantages', models.CharField(blank=True, max_length=255, null=True, verbose_name='Преимущество')),
                ('deteil_description', models.TextField(blank=True, null=True, verbose_name='Детальное описание')),
                ('square', models.IntegerField(blank=True, null=True, verbose_name='Площадь')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('all_floor', models.IntegerField(blank=True, null=True, verbose_name='Всего этажей')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена объекта')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.type')),
            ],
        ),
    ]
