# Generated by Django 5.1 on 2024-08-27 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_building_type_alter_oldbuilding_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='user',
        ),
        migrations.RemoveField(
            model_name='building',
            name='type',
        ),
        migrations.AddField(
            model_name='building',
            name='all_floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего этажей'),
        ),
        migrations.AddField(
            model_name='building',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='building',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена объекта'),
        ),
        migrations.AddField(
            model_name='building',
            name='square',
            field=models.IntegerField(blank=True, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='building',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Квартира'), ('2', 'Дом'), ('3', 'Дача'), ('4', 'Земельный участок')], default='house', max_length=100, verbose_name='Категория недвижимости'),
        ),
        migrations.CreateModel(
            name='TypeChoise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_choise', models.CharField(choices=[('1', 'Комплексы (ЖК, Коттеджные поселки)'), ('2', 'Отдельные объекты (Вторичка, частные объявления)'), ('3', 'Сайт отдельного ЖК')], default='1', max_length=100, verbose_name='Тип недвижимости')),
                ('category', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом')], default='1', max_length=100, verbose_name='Категория недвижимости')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='type_choise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.typechoise'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OldBuilding',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
