# Generated by Django 5.1 on 2024-08-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_type_user_remove_building_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='down_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст под названием'),
        ),
        migrations.AlterField(
            model_name='building',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Наименование объекта'),
        ),
        migrations.AlterField(
            model_name='building',
            name='top_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст над названием'),
        ),
        migrations.AlterField(
            model_name='typechoise',
            name='category',
            field=models.CharField(choices=[('1', 'Квартира'), ('2', 'Дом')], default='1', max_length=100, verbose_name='Категория недвижимости'),
        ),
    ]
