# Generated by Django 5.1 on 2024-08-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_typechoise_type_choise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='building',
            name='description2',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
