# Generated by Django 5.1 on 2024-08-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_description_building_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slyder_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Главное фото объекта'),
        ),
        migrations.RemoveField(
            model_name='building',
            name='image_slider',
        ),
        migrations.AddField(
            model_name='building',
            name='image_slider',
            field=models.ManyToManyField(blank=True, to='main.image'),
        ),
    ]
