# Generated by Django 5.1 on 2024-08-27 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_building_image_slider_delete_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='image_slider',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='slyder_images/')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typechoise')),
            ],
        ),
    ]
