# Generated by Django 5.1 on 2024-08-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_building_image_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_s',
            field=models.ImageField(blank=True, upload_to='slyder_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
