# Generated by Django 5.1 on 2024-08-27 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_image_image_s_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.building'),
        ),
    ]
