# Generated by Django 5.1 on 2024-08-28 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_building_image_alter_image_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Главное фото объекта'),
        ),
        migrations.AlterField(
            model_name='image',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.building'),
        ),
    ]
