# Generated by Django 5.1 on 2024-08-29 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_image_image_building_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_plans',
            field=models.ImageField(blank=True, upload_to='plans_images/'),
        ),
        migrations.AlterField(
            model_name='building',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Квартира'), ('2', 'Дом'), ('3', 'Дача'), ('4', 'Земельный участок')], default='1', max_length=100, verbose_name='Категория недвижимости'),
        ),
        migrations.AlterField(
            model_name='building',
            name='title',
            field=models.CharField(blank=True, default='Без названия', max_length=255, null=True, verbose_name='Наименование объекта'),
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_building', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип жилья')),
                ('quanty_room', models.IntegerField(blank=True, null=True, verbose_name='Колличество комнат')),
                ('total_area_from', models.IntegerField(blank=True, null=True, verbose_name='Общая площадь от')),
                ('total_area_upto', models.IntegerField(blank=True, null=True, verbose_name='Общая площадь до')),
                ('price_from', models.IntegerField(blank=True, null=True, verbose_name='Общая площадь до')),
                ('price_upto', models.IntegerField(blank=True, null=True, verbose_name='Общая площадь до')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.building')),
            ],
        ),
    ]
