# Generated by Django 5.1 on 2024-08-30 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_image_image_plans_alter_building_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='main.building'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='price_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена от'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='price_upto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена до'),
        ),
    ]
