# Generated by Django 5.1 on 2024-08-30 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_plans_building_alter_plans_price_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='plans',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.plans'),
            preserve_default=False,
        ),
    ]
