# Generated by Django 5.1 on 2024-09-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_building_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='is_visible',
        ),
    ]
