# Generated by Django 5.1 on 2024-08-25 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('tg_link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка Telegram')),
                ('whatsapp', models.CharField(blank=True, max_length=255, verbose_name='WhatsApp')),
                ('description', models.TextField(blank=True, null=True, verbose_name='')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='Номеp')),
                ('vk_link', models.TextField(blank=True, null=True, verbose_name='')),
                ('instagram_link', models.TextField(blank=True, null=True, verbose_name='')),
                ('youtube_link', models.TextField(blank=True, null=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='Номеp')),
                ('decoding', models.CharField(blank=True, max_length=255, verbose_name='Расшифровка')),
                ('text_under_number', models.CharField(blank=True, max_length=255, verbose_name='Подпись под номером')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ccskrf')),
            ],
        ),
        migrations.CreateModel(
            name='Choise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование объекта')),
                ('type', models.CharField(choices=[('1', 'Комплексы (ЖК, Коттеджные поселки)'), ('2', 'Отдельные объекты (Вторичка, частные объявления)'), ('3', 'Сайт отдельного ЖК')], default='1', max_length=100, verbose_name='Тип недвижимости')),
                ('category', models.CharField(blank=True, choices=[('apartment', 'Квартира'), ('house', 'Дом')], default='house', max_length=100, verbose_name='Категория недвижимости')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FirstScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=255, verbose_name='Имя сайта')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок сайта')),
                ('category', models.CharField(blank=True, choices=[('apartment', 'Квартира'), ('house', 'Дом')], default='house', max_length=100, verbose_name='Категория недвижимости')),
                ('prefix', models.CharField(blank=True, choices=[('1', ''), ('2', 'от'), ('3', 'до')], default='2', max_length=100, verbose_name='Префикс цены')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена объекта')),
                ('question1', models.CharField(blank=True, max_length=255, verbose_name='Вопрос №1')),
                ('variants1', models.TextField(blank=True, null=True, verbose_name='Варианты №1')),
                ('question2', models.CharField(blank=True, max_length=255, verbose_name='Вопрос №2')),
                ('variants2', models.TextField(blank=True, null=True, verbose_name='Варианты №2')),
                ('question3', models.CharField(blank=True, max_length=255, verbose_name='Вопрос №3')),
                ('variants3', models.TextField(blank=True, null=True, verbose_name='Варианты №3')),
                ('question4', models.CharField(blank=True, max_length=255, verbose_name='Вопрос №4')),
                ('variants4', models.TextField(blank=True, null=True, verbose_name='Варианты №4')),
                ('choise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.choise')),
            ],
        ),
    ]
