# Generated by Django 5.1 on 2024-08-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstscreen',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя сайта'),
        ),
    ]
