# Generated by Django 5.1 on 2024-08-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_firstscreen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstscreen',
            name='category',
            field=models.CharField(blank=True, choices=[('apartment', 'Квартира'), ('house', 'Дом')], default='apartment', max_length=100, verbose_name='Категория недвижимости'),
        ),
        migrations.AlterField(
            model_name='firstscreen',
            name='name',
            field=models.CharField(blank=True, default='Город в Самаре', max_length=255, verbose_name='Имя сайта'),
        ),
        migrations.AlterField(
            model_name='firstscreen',
            name='price',
            field=models.IntegerField(blank=True, default=6800000, null=True, verbose_name='Цена объекта'),
        ),
        migrations.AlterField(
            model_name='firstscreen',
            name='question1',
            field=models.CharField(blank=True, default='какое количество комнат необходимо?', max_length=255, verbose_name='Вопрос №1'),
        ),
        migrations.AlterField(
            model_name='firstscreen',
            name='question2',
            field=models.CharField(blank=True, default='какой район вы рассматриваете?', max_length=255, verbose_name='Вопрос №2'),
        ),
        migrations.AlterField(
            model_name='firstscreen',
            name='question3',
            field=models.CharField(blank=True, default='какой бюджет планируете на покупку?', max_length=255, verbose_name='Вопрос №3'),
        ),
        migrations.AlterField(
            model_name='firstscreen',
            name='title',
            field=models.CharField(blank=True, default='Купить квартиру в новостройках Самары', max_length=255, verbose_name='Заголовок сайта'),
        ),
        migrations.AlterField(
            model_name='firstscreen',
            name='variants1',
            field=models.TextField(blank=True, default='Студия \n 1 комнатная \n 2 комнатная \n 3 комнатная \n 4 и более', null=True, verbose_name='Варианты №1'),
        ),
        migrations.AlterField(
            model_name='firstscreen',
            name='variants2',
            field=models.TextField(blank=True, default='Любой район \n Куйбышевский район \n Ленинский район \n Железнодорожный район \n Октябрьский район \n Советский район \n Промышленный район', null=True, verbose_name='Варианты №2'),
        ),
        migrations.AlterField(
            model_name='firstscreen',
            name='variants3',
            field=models.TextField(blank=True, default='около 4 млн. \n до 4,5 млн. \n до 5 млн. \n до 5,5 млн. \n до 6 млн. \n до 6,5 млн. \n более 7 млн.', null=True, verbose_name='Варианты №3'),
        ),
    ]
