# Generated by Django 5.1 on 2024-08-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_firstscreen_category_alter_firstscreen_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstscreen',
            name='variants1',
            field=models.TextField(blank=True, default='Студия\n1 комнатная\n2 комнатная\n3 комнатная\n4 и более', null=True, verbose_name='Варианты №1'),
        ),
        migrations.AlterField(
            model_name='firstscreen',
            name='variants2',
            field=models.TextField(blank=True, default='Любой район\nКуйбышевский район\nЛенинский район\nЖелезнодорожный район\nОктябрьский район\nСоветский район\nПромышленный район', null=True, verbose_name='Варианты №2'),
        ),
        migrations.AlterField(
            model_name='firstscreen',
            name='variants3',
            field=models.TextField(blank=True, default='около 4 млн.\nдо 4,5 млн.\nдо 5 млн.\nдо 5,5 млн.\nдо 6 млн.\nдо 6,5 млн.\nболее 7 млн.', null=True, verbose_name='Варианты №3'),
        ),
    ]
