# Generated by Django 5.1 on 2024-09-02 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_firstscreen_variants1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='choise',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.choise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sites',
            name='choise',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='sites.choise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, default='Здравствуйте. Интересует покупка квартиры!', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default='profile_images_contact/free-icon-user-219983.png', null=True, upload_to='profile_images_contact/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(blank=True, default='+79229988776', max_length=255, verbose_name='Номеp'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tg_link',
            field=models.CharField(blank=True, default='t.me/', max_length=255, verbose_name='Ссылка Telegram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(blank=True, default='+79229988776', max_length=255, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='firstscreen',
            name='image',
            field=models.ImageField(blank=True, default='images/default_image.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='decoding',
            field=models.CharField(blank=True, default='агентство недвижимости', max_length=255, verbose_name='Расшифровка'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='number',
            field=models.CharField(blank=True, default='+79229988776', max_length=255, verbose_name='Номеp'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='text_under_number',
            field=models.CharField(blank=True, default='с 9.00 до 20.00', max_length=255, verbose_name='Подпись под номером'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_icons', models.ImageField(blank=True, default='profile_images_contact/free-icon-user-219983.png', null=True, upload_to='icon_images/')),
                ('sites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_icons', to='sites.sites')),
            ],
        ),
    ]
