# Generated by Django 5.1 on 2024-09-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_contact_choise_sites_choise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='vk_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
    ]
