# Generated by Django 5.1 on 2024-09-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_rename_image_contact_image_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='name',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Название компании'),
        ),
    ]
