# Generated by Django 5.1 on 2024-09-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_logo_alter_contact_image_contacts_sites_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image_contacts',
            field=models.ImageField(blank=True, default='profile_images_contact/default_image_contacts.jpg', null=True, upload_to='profile_images_contact/'),
        ),
    ]
