# Generated by Django 5.1 on 2024-09-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_alter_contact_image_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image_contacts',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images_contact/'),
        ),
        migrations.AlterField(
            model_name='firstscreen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
