# Generated by Django 5.1 on 2024-09-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_alter_contact_image_contacts_alter_firstscreen_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Иконка'),
        ),
    ]
