# Generated by Django 5.1 on 2024-09-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_alter_contact_image_contacts_alter_firstscreen_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image_contacts',
            field=models.ImageField(blank=True, default='profile_images_contact/default_image.jpg', null=True, upload_to='profile_images_contact/'),
        ),
    ]
