# Generated by Django 5.1 on 2024-09-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_plans_total_area_from_and_more'),
        ('sites', '0018_choise_selected_buildings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choise',
            name='selected_buildings',
            field=models.ManyToManyField(blank=True, related_name='choises', to='main.building'),
        ),
    ]
