# Generated by Django 5.1 on 2024-09-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0019_alter_choise_selected_buildings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstscreen',
            old_name='name',
            new_name='name_company',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='name',
            new_name='name_sites',
        ),
    ]
