# Generated by Django 5.1 on 2024-09-17 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0020_rename_name_firstscreen_name_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_seo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назване страницы')),
                ('url_link_seo', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('deskription_seo', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('key_word_seo', models.TextField(blank=True, null=True, verbose_name='Ключевые слова')),
                ('choise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.choise')),
            ],
        ),
    ]
